# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        docker pull mysql:latest
        docker pull redis:latest

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Dependencies
      run: go mod download

    # 安全
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

      # 代码风格
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.53

    - name: Unit Test
      run: go test -v ./...
